#! /usr/bin/env python
# -*- python -*-

#####################################################################################################

import sys

from optparse import OptionParser

from PyQt4 import QtGui, QtCore, uic

#####################################################################################################

from DviViewerMainWindow import MainWindow

#####################################################################################################
#
# Application
#

class Application(QtGui.QApplication):

    ################################################

    def __init__(self, dvi_file):

        QtGui.QApplication.__init__(self, sys.argv)

        self.main_window = MainWindow(dvi_file)

        self.main_window.show()

#####################################################################################################
#
# Main
#
#####################################################################################################

if __name__ == "__main__":

    usage = 'usage: %prog [options]'

    parser = OptionParser(usage)

    opt, args = parser.parse_args()

    if len(args) > 0:
        dvi_file = args[0]
    else:
        dvi_file = None

    application = Application(dvi_file)

    application.exec_()

#####################################################################################################
#
# End
#
#####################################################################################################
