#! /usr/bin/env python
# -*- python -*-

#####################################################################################################

import sys

from optparse import OptionParser

from PyQt4 import QtGui, QtCore, uic

#####################################################################################################

from PkFontViewerMainWindow import MainWindow

#####################################################################################################
#
# Application
#

class Application(QtGui.QApplication):

    ################################################

    def __init__(self, font_name = None):

        QtGui.QApplication.__init__(self, sys.argv)

        self.main_window = MainWindow(font_name)

        self.main_window.show()

#####################################################################################################
#
# Main
#
#####################################################################################################

if __name__ == "__main__":

    usage = 'usage: %prog [options]'

    parser = OptionParser(usage)

    opt, args = parser.parse_args()

    if args > 0:
        font_name = args[0]
    else:
        font_name = None

    application = Application(font_name)

    application.exec_()

#####################################################################################################
#
# End
#
#####################################################################################################
